export PATH=$HOME/Library/Python/2.7/bin:$PATH
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. $HOME/Library/Python/2.7/lib/python/site-packages/powerline/bindings/bash/powerline.sh
