source ~/bin/.git-completion.bash
source ~/bin/.git-prompt.bash

export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_SHOWCOLORHINTS=true

export PS1='👼 \[\e[0;36m\]\[\e[0;36m\] \W\[\033[0;35m\]$(__git_ps1 " (%s)")\[\e[0m\]: '

alias ls='exa --grid --classify'
alias ll='exa --long --classify --git --header --binary --group --modified --accessed --time-style=long-iso'
